version: '2'
services:
  db:
    image: postgres
    container_name: q-pg
  web:
    build: .
    container_name: q-rails
    command: bash -c "bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ${PWD}:/rails-app
    ports:
      - "3000:3000"
      - "4331:4331"
    depends_on:
      - db
